name: Java Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 1.8
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build with Maven
    - name: Build and package with Maven
      run: mvn clean package

    # Verify shaded JAR
    - name: Verify shaded JAR
      run: |
        ls -la target
        if [[ -f target/jb-hello-world-maven-0.2.0-shaded.jar ]]; then
          echo "Shaded JAR created successfully."
        else
          echo "Shaded JAR not found!" && exit 1
        fi
